# -*- coding: utf-8 -*-
"""banglaT5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZjTmgJbNKm5C8BRd31LG_L0EsrE9NlTy

# BanglaT5
"""

!pip install transformers
!pip install datasets

import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
from transformers import T5Tokenizer, T5ForSequenceClassification, Trainer, TrainingArguments
from datasets import Dataset

# Load dataset
df = pd.read_csv("fake.csv")

print(df.columns)

!pip install transformers datasets torch scikit-learn pandas

df = df.rename(columns={"Review": "text", "Label": "label"})
print(df.columns)

train_texts, test_texts, train_labels, test_labels = train_test_split(df["text"], df["label"], test_size=0.2, random_state=42)

tokenizer = T5Tokenizer.from_pretrained("csebuetnlp/banglat5")

# Tokenize data
def tokenize_function(examples):
    return tokenizer(examples["text"], padding="max_length", truncation=True, max_length=512)

# Create datasets
train_data = Dataset.from_pandas(pd.DataFrame({"text": train_texts, "label": train_labels}))
test_data = Dataset.from_pandas(pd.DataFrame({"text": test_texts, "label": test_labels}))

train_data = train_data.map(tokenize_function, batched=True)
test_data = test_data.map(tokenize_function, batched=True)

# Load model
model = T5ForSequenceClassification.from_pretrained("csebuetnlp/banglat5", num_labels=2)

# Define training arguments
training_args = TrainingArguments(
    output_dir="./results",
    evaluation_strategy="epoch",
    save_strategy="epoch",
    learning_rate=2e-5,
    per_device_train_batch_size=4,
    per_device_eval_batch_size=4,
    num_train_epochs=3,
    weight_decay=0.01,
    logging_dir="./logs",
    logging_steps=10,
)

#Trainer function
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_data,
    eval_dataset=test_data,
)

# Train model
trainer.train()

# Evaluate model
def compute_metrics(pred):
    predictions = torch.argmax(torch.tensor(pred.predictions), dim=1)
    labels = torch.tensor(pred.label_ids)

    accuracy = accuracy_score(labels, predictions)
    precision = precision_score(labels, predictions)
    recall = recall_score(labels, predictions)
    f1 = f1_score(labels, predictions)

    return {"accuracy": accuracy, "precision": precision, "recall": recall, "f1": f1}

metrics = trainer.evaluate()
print(metrics)

print("Evaluation Metrics:")
print(f"Accuracy: {metrics['accuracy']:.4f}")
print(f"Precision: {metrics['precision']:.4f}")
print(f"Recall: {metrics['recall']:.4f}")
print(f"F1 Score: {metrics['f1']:.4f}")