# -*- coding: utf-8 -*-
"""Banglabert.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kiSeZVBTnQ4-wCEOQgkBLZs-a6cA7u-k
"""

# ✅ Install required libraries
!pip install -q torch transformers datasets accelerate scikit-learn
!pip install -q datasets

# ✅ Load necessary libraries
from datasets import load_dataset, DatasetDict
import pandas as pd
import numpy as np
import torch
import json
from transformers import AutoTokenizer, AutoModelForSequenceClassification, TrainingArguments, Trainer
from sklearn.metrics import classification_report, accuracy_score, precision_recall_fscore_support
from google.colab import files
import shutil

# ✅ Load the dataset
dataset = load_dataset("shawon95/Bengali-Fake-Review-Dataset")

# ✅ Check available dataset splits
print("Available dataset splits:", dataset.keys())

from datasets import DatasetDict

# ✅ Check if 'test' dataset exists; if not, create a test split
if "test" not in dataset.keys():
    print("⚠️ No 'test' dataset found! Splitting dataset into train & test...")

    # Ensure dataset is shuffled before splitting
    dataset = dataset["train"].shuffle(seed=42)

    # Split dataset: 80% for training, 20% for testing
    dataset_split = dataset.train_test_split(test_size=0.2, seed=42)

    # Store the new train-test split in a DatasetDict
    dataset = DatasetDict({
        "train": dataset_split["train"],
        "test": dataset_split["test"]
    })

    print("✅ New dataset splits created:", dataset.keys())
else:
    print("✅ Train & Test sets are already available!")

# ✅ Remove missing values (NaN) from the dataset
def remove_missing_values(dataset):
    df = pd.DataFrame(dataset)
    df.dropna(inplace=True)  # Remove NaN rows
    return dataset.filter(lambda x: x["Review"] is not None and x["Label"] is not None)

dataset["train"] = remove_missing_values(dataset["train"])
dataset["test"] = remove_missing_values(dataset["test"])

print("✅ Missing values removed!")

# ✅ Load BanglaBERT tokenizer
from transformers import AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained("csebuetnlp/banglabert")

def tokenize_function(example):
    tokenized_review = tokenizer(example["Review"], padding="max_length", truncation=True, max_length=256)
    tokenized_review["labels"] = example["Label"]  # Add labels explicitly
    return tokenized_review

# ✅ Tokenize the dataset
tokenized_datasets = dataset.map(tokenize_function, batched=True)


# ✅ Apply tokenization
tokenized_datasets = dataset.map(tokenize_function, batched=True)

# ✅ Remove "Review" column and format for PyTorch
tokenized_datasets = tokenized_datasets.remove_columns(["Review"])
tokenized_datasets.set_format("torch")

# ✅ Show a sample tokenized review
print("✅ Sample tokenized review:", tokenized_datasets["train"][0])

# ✅ Load pre-trained BanglaBERT model for classification
from transformers import AutoModelForSequenceClassification

model = AutoModelForSequenceClassification.from_pretrained("shawon95/BengaliFakeReviewDetection", num_labels=2)

# ✅ Define training arguments (Optimized for Colab Free)
training_args = TrainingArguments(
    output_dir="./results",
    eval_strategy="epoch",
    save_strategy="epoch",
    learning_rate=2e-5,
    per_device_train_batch_size=4,  # Lower batch size to avoid memory issues
    per_device_eval_batch_size=4,
    gradient_accumulation_steps=4,  # Helps fit in Colab Free GPU
    num_train_epochs=3,
    weight_decay=0.01,
    logging_dir="./logs",
    logging_steps=10,
    fp16=True,  # Enable mixed precision for better performance
)

# ✅ Initialize Trainer
#API KEY: 15a26bfde02e39ba547185222150f57c5c5d8e02
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_datasets["train"],  # Train dataset
    eval_dataset=tokenized_datasets["test"],    # Test dataset
    tokenizer=tokenizer,
)

# ✅ Train the model
print("🚀 Training Started...")
trainer.train()
print("✅ Training Completed!")

import numpy as np
from sklearn.metrics import accuracy_score, classification_report

# ✅ Function to compute accuracy, precision, recall, and F1-score (Fake & Non-Fake Separately)
def compute_metrics(eval_pred):
    logits, labels = eval_pred  # Extract model outputs
    predictions = np.argmax(logits, axis=-1)  # Convert logits to class predictions

    # ✅ Compute accuracy
    acc = accuracy_score(labels, predictions)
    precision, recall, f1, _ = precision_recall_fscore_support(labels, predictions, average="binary")

    # ✅ Compute Fake vs Non-Fake metrics separately
    report = classification_report(labels, predictions, target_names=["Non-Fake", "Fake"], digits=4, output_dict=True)

    # Extract per-class F1-scores
    fake_f1 = report["Fake"]["f1-score"]
    non_fake_f1 = report["Non-Fake"]["f1-score"]
    weighted_f1 = report["weighted avg"]["f1-score"]

    return {
        "accuracy": acc,
        "Fake F1-score": fake_f1,
        "Non-Fake F1-score": non_fake_f1,
        "Weighted F1-score": weighted_f1
    }

# ✅ Run evaluation properly
predictions, labels, _ = trainer.predict(tokenized_datasets["test"])

# ✅ Convert logits to class labels (0 or 1)
predicted_classes = np.argmax(predictions, axis=-1)

# ✅ Ensure labels are in the correct format
labels = labels.astype(int)

# ✅ Compute accuracy, precision, recall, and F1-score
from sklearn.metrics import accuracy_score, precision_recall_fscore_support, classification_report

# ✅ Compute Accuracy
accuracy = accuracy_score(labels, predicted_classes)

# ✅ Compute Precision, Recall, and F1-score Separately
precision, recall, f1, _ = precision_recall_fscore_support(labels, predicted_classes, average=None)

# ✅ Print Fake vs Non-Fake Scores Separately
print("📊 Fake vs Non-Fake Class Report:")
print(classification_report(labels, predicted_classes, target_names=["Non-Fake", "Fake"], digits=4))

# ✅ Save results as JSON
import json
results = {
    "Accuracy": accuracy,
    "Fake F1-score": f1[1],  # Fake class
    "Non-Fake F1-score": f1[0],  # Non-Fake class
    "Weighted F1-score": precision_recall_fscore_support(labels, predicted_classes, average="weighted")[2]
}

with open("evaluation_results.json", "w") as f:
    json.dump(results, f)

# ✅ Print Results
print("✅ Final Metrics:")
print(results)

# ✅ Save the fine-tuned model
trainer.save_model("./banglabert-bfrd")
tokenizer.save_pretrained("./banglabert-bfrd")

# ✅ Zip the model folder
shutil.make_archive("banglabert-bfrd", 'zip', "./banglabert-bfrd")

# ✅ Download the model and evaluation results
files.download("banglabert-bfrd.zip")
files.download("evaluation_results.json")

import numpy as np
import matplotlib.pyplot as plt

# ✅ Metrics
metrics = ["Accuracy", "Precision", "Recall", "F1-score"]
scores = [0.9773, 0.9818, 0.9934, 0.9876]  # BanglaBERT Scores

# ✅ Closing the circle
angles = np.linspace(0, 2 * np.pi, len(metrics), endpoint=False).tolist()
scores += scores[:1]
angles += angles[:1]

# ✅ Plot Radar Chart
fig, ax = plt.subplots(figsize=(6,6), subplot_kw=dict(polar=True))
ax.plot(angles, scores, label="BanglaBERT", linewidth=2, color='blue')
ax.fill(angles, scores, alpha=0.2, color='blue')

ax.set_xticks(angles[:-1])
ax.set_xticklabels(metrics, fontsize=12, fontweight="bold", rotation=15)

plt.title("BanglaBERT Performance", fontsize=14, fontweight="bold", pad=20)
plt.ylim(0.8, 1)  # ✅ Keep scale consistent
plt.legend(loc="upper right")
plt.show()

# ✅ Install required libraries
!pip install -q matplotlib seaborn numpy

# ✅ Load necessary libraries
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

# ✅ Take User Input for Model Evaluation Results
print("\n🔹 Enter evaluation metrics for each model (values between 0 and 1) 🔹")

models = ["BanglaBERT", "XLM-R", "mBERT"]
metrics = ["Accuracy", "Precision", "Recall", "F1-score"]
user_results = {}

for model in models:
    print(f"\n🟢 Enter values for {model}:")
    user_results[model] = {}
    for metric in metrics:
        while True:
            try:
                value = float(input(f"{metric} (0-1) for {model}: ")) * 100  # Convert to percentage
                if 0 <= value <= 100:
                    user_results[model][metric] = value
                    break
                else:
                    print("❌ Invalid input. Enter a value between 0 and 1.")
            except ValueError:
                print("❌ Invalid input. Please enter a number.")

# ✅ Convert user input into a structured NumPy array for visualization
data = np.array([
    [user_results["BanglaBERT"]["Accuracy"], user_results["BanglaBERT"]["Precision"],
     user_results["BanglaBERT"]["Recall"], user_results["BanglaBERT"]["F1-score"]],

    [user_results["XLM-R"]["Accuracy"], user_results["XLM-R"]["Precision"],
     user_results["XLM-R"]["Recall"], user_results["XLM-R"]["F1-score"]],

    [user_results["mBERT"]["Accuracy"], user_results["mBERT"]["Precision"],
     user_results["mBERT"]["Recall"], user_results["mBERT"]["F1-score"]],
])

# ✅ Function to plot accuracy comparison
def plot_accuracy():
    plt.figure(figsize=(6, 4))
    plt.plot(models, data[:, 0], marker="o", linestyle="-", color="blue", linewidth=2, markersize=8)
    plt.xlabel("Models")
    plt.ylabel("Accuracy (%)")
    plt.title("Accuracy Comparison Across Models")
    plt.ylim(50, 100)
    plt.grid(True, linestyle="--", alpha=0.7)
    plt.show()

# ✅ Function to plot heatmap of evaluation metrics
def plot_heatmap():
    plt.figure(figsize=(6, 4))
    sns.heatmap(data, annot=True, cmap="coolwarm", xticklabels=metrics, yticklabels=models, fmt=".1f")
    plt.xlabel("Metrics")
    plt.ylabel("Models")
    plt.title("Model Performance Heatmap")
    plt.show()

# ✅ Function to plot radar chart (Spider Chart) with adjusted text placement
def plot_radar_chart():
    angles = np.linspace(0, 2 * np.pi, len(metrics), endpoint=False).tolist()
    angles += angles[:1]  # Closing the circle

    fig, ax = plt.subplots(figsize=(7, 7), subplot_kw=dict(polar=True))  # ✅ Increase figure size

    for i, model in enumerate(models):
        values = list(data[i]) + [data[i][0]]  # Repeat first value at end
        ax.plot(angles, values, label=model, linewidth=2)
        ax.fill(angles, values, alpha=0.1)

    # ✅ Fix text overlap by increasing padding
    ax.set_xticks(angles[:-1])
    ax.set_xticklabels(metrics, fontsize=12, fontweight="bold", rotation=15)  # ✅ Rotate labels slightly

    plt.title("Performance Comparison of Models", fontsize=14, fontweight="bold", pad=20)  # ✅ Adjust title spacing
    plt.legend(loc="upper right", bbox_to_anchor=(1.2, 1.1))  # ✅ Move legend outside plot
    plt.show()

# ✅ Run the improved radar chart
plot_radar_chart()


# ✅ Run Plots
plot_accuracy()
plot_heatmap()