# -*- coding: utf-8 -*-
"""Copy of BanglaRoBERTaXLM.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nF7D3FZU9DdYbnhtoD76-IFc9vOGPvzp
"""

# ✅ Install required libraries
!pip install -q torch transformers datasets accelerate scikit-learn

import pandas as pd
from datasets import load_dataset
from sklearn.model_selection import train_test_split
from transformers import XLMRobertaTokenizer, XLMRobertaForSequenceClassification, Trainer, TrainingArguments
from sklearn.metrics import accuracy_score, precision_recall_fscore_support
import torch

# ✅ Load dataset
dataset = load_dataset("shawon95/Bengali-Fake-Review-Dataset")

# Check available splits and create a test split if necessary
if 'test' not in dataset:
    print("No 'test' split found! Creating a split from the 'train' dataset.")

    # Shuffle and split the train dataset into train and test (80%-20%)
    dataset_split = dataset['train'].train_test_split(test_size=0.2, seed=42)

    # Store the new train-test split in the dataset
    dataset = dataset_split

# Convert to pandas DataFrame
train_df = pd.DataFrame(dataset['train'])
test_df = pd.DataFrame(dataset['test'])

# Print dataset heads
print("Train Dataset Head:")
print(train_df.head())

print("Test Dataset Head:")
print(test_df.head())

# ✅ Load the XLM-RoBERTa Tokenizer and Model
tokenizer = XLMRobertaTokenizer.from_pretrained("xlm-roberta-base")
model = XLMRobertaForSequenceClassification.from_pretrained("xlm-roberta-base", num_labels=2)

# ✅ Tokenize the dataset and ensure 'Label' is included
def tokenize_function(examples):
    return tokenizer(examples['Review'], padding='max_length', truncation=True)

train_dataset = dataset['train'].map(tokenize_function, batched=True)
test_dataset = dataset['test'].map(tokenize_function, batched=True)

# ✅ Add labels as part of the dataset
train_dataset = train_dataset.rename_column("Label", "labels")
test_dataset = test_dataset.rename_column("Label", "labels")

# ✅ Set format for PyTorch
train_dataset.set_format(type='torch', columns=['input_ids', 'attention_mask', 'labels'])
test_dataset.set_format(type='torch', columns=['input_ids', 'attention_mask', 'labels'])

## ✅ Define metrics function
def compute_metrics(p):
    preds = p.predictions.argmax(axis=-1)
    labels = p.label_ids
    acc = accuracy_score(labels, preds)
    precision, recall, f1, _ = precision_recall_fscore_support(labels, preds, average='binary')
    return {
        'accuracy': acc,
        'precision': precision,
        'recall': recall,
        'f1': f1
    }

#✅ Define Trainer arguments
training_args = TrainingArguments(
    output_dir='./results',
    evaluation_strategy="epoch",
    learning_rate=2e-5,
    per_device_train_batch_size=16,
    per_device_eval_batch_size=16,
    num_train_epochs=3,
    weight_decay=0.01,
    logging_dir='./logs',
)

# ✅ Define Trainer
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=test_dataset,
    compute_metrics=compute_metrics
)

# ✅ Train the model
trainer.train()

# ✅ Evaluate the model
eval_results = trainer.evaluate()

# ✅ Print evaluation results (Accuracy, Precision, Recall, F1-Score)
print("\nEvaluation Results:")
print(eval_results)