# -*- coding: utf-8 -*-
"""mbert-fakeReview.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PrzRD6oeycjRYVMSuiQsHw3b_eF6WJV1
"""

# Step 1: Install Required Libraries
!pip install -q transformers accelerate datasets peft bitsandbytes

# Step 2: Import Libraries
import torch
from transformers import AutoTokenizer, AutoModelForSequenceClassification, TrainingArguments, Trainer
from datasets import load_dataset
from peft import LoraConfig, get_peft_model, TaskType
import numpy as np
from sklearn.metrics import accuracy_score, precision_recall_fscore_support
import os
import json
import shutil
from google.colab import files
from huggingface_hub import notebook_login

# Authenticate Hugging Face
notebook_login()

# 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

# Step 3: Load the Tokenizer & Model
import torch
from transformers import AutoTokenizer, AutoModelForSequenceClassification

model_name = "bert-base-multilingual-cased"  # mBERT model

# ✅ Load Tokenizer
tokenizer = AutoTokenizer.from_pretrained(model_name)

# ✅ Check GPU availability
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"✅ Using Device: {device}")

# ✅ Load Pretrained mBERT Model for Classification
model = AutoModelForSequenceClassification.from_pretrained(
    model_name, num_labels=2
).to(device)

print("✅ mBERT Model Loaded Successfully!")

# Step 4: Load & Preprocess Dataset
from datasets import load_dataset

dataset = load_dataset("shawon95/Bengali-Fake-Review-Dataset")

if "test" not in dataset.keys():
    dataset_split = dataset["train"].train_test_split(test_size=0.2, seed=42)
    dataset = {
        "train": dataset_split["train"],
        "test": dataset_split["test"]
    }

print("✅ Dataset Loaded and Split!")

# Tokenization Function
def tokenize_function(examples):
    return tokenizer(examples["Review"], padding="max_length", truncation=True, max_length=256)

# Apply Tokenization
tokenized_datasets = dataset["train"].map(tokenize_function, batched=True)
tokenized_datasets_test = dataset["test"].map(tokenize_function, batched=True)

tokenized_datasets.set_format("torch")
tokenized_datasets_test.set_format("torch")

print("✅ Tokenization Completed!")

# Step 5: Configure LoRA for Fine-Tuning
from peft import LoraConfig, get_peft_model, TaskType

lora_config = LoraConfig(
    task_type=TaskType.SEQ_CLS,  # Sequence classification task
    inference_mode=False,
    r=8,
    lora_alpha=32,
    lora_dropout=0.1
)

# Apply LoRA to mBERT
model = get_peft_model(model, lora_config)
model.print_trainable_parameters()

print("✅ LoRA Applied Successfully!")

# Step 6: Define Training Arguments with Checkpointing
from transformers import TrainingArguments, Trainer

training_args = TrainingArguments(
    output_dir="./mb-bert_results",
    evaluation_strategy="epoch",
    save_strategy="epoch",
    save_total_limit=2,
    save_steps=500,  # Saves model every 500 steps
    load_best_model_at_end=True,
    learning_rate=2e-5,
    per_device_train_batch_size=4,
    per_device_eval_batch_size=4,
    num_train_epochs=3,
    weight_decay=0.01,
    logging_dir="./logs",
    logging_steps=10,
    fp16=True if torch.cuda.is_available() else False,  # Enable FP16 if GPU is available
    report_to="none",
    push_to_hub=False
)

print("✅ Training Arguments Set!")

# Step 7: Define Evaluation Metrics
import numpy as np
from sklearn.metrics import accuracy_score, precision_recall_fscore_support

def compute_metrics(eval_pred):
    logits, labels = eval_pred
    predictions = np.argmax(logits, axis=-1)

    acc = accuracy_score(labels, predictions)
    precision, recall, f1, _ = precision_recall_fscore_support(labels, predictions, average="binary")

    return {
        "accuracy": acc,
        "precision": precision,
        "recall": recall,
        "f1-score": f1
    }

print("✅ Evaluation Metrics Defined!")

# Step 8: Resume from Checkpoint (if exists)
import os

checkpoint_path = None
if os.path.exists("./mb-bert_results") and len(os.listdir("./mb-bert_results")) > 0:
    checkpoint_path = "./mb-bert_results"
    print(f"🔄 Resuming from last checkpoint: {checkpoint_path}")
else:
    print("🆕 No checkpoint found, starting fresh training!")

#step 8.1
from transformers import AutoModelForSequenceClassification

# ✅ Load Model with Correct Loss Calculation
model = AutoModelForSequenceClassification.from_pretrained(model_name, num_labels=2)

# ✅ Apply LoRA
model = get_peft_model(model, lora_config)

# step- 8.2
from transformers import AutoTokenizer
from datasets import load_dataset

# Load Dataset (replace this with your dataset loading code)
dataset = load_dataset("imdb")  # Example, replace with your dataset

# Load Tokenizer
tokenizer = AutoTokenizer.from_pretrained("bert-base-multilingual-cased")

# Define Tokenization Function with Labels
def tokenize_function(examples):
    return tokenizer(examples['text'], padding='max_length', truncation=True)

# Apply Tokenization & Add Labels
tokenized_datasets = dataset.map(tokenize_function, batched=True)
tokenized_datasets = tokenized_datasets.rename_column("label", "labels")  # Ensure labels are properly named

# ✅ Ensure labels are added in the training and eval datasets
train_dataset = tokenized_datasets["train"]
eval_dataset = tokenized_datasets["test"]

from transformers import Trainer
import torch.nn.functional as F

class CustomTrainer(Trainer):
    def compute_loss(self, model, inputs, return_outputs=False, **kwargs):
        labels = inputs.pop("labels")  # Extract 'labels' key
        outputs = model(**inputs)  # Forward pass
        logits = outputs.logits
        loss = F.cross_entropy(logits, labels)  # Compute loss manually

        return (loss, outputs) if return_outputs else loss

trainer = CustomTrainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=eval_dataset,
    tokenizer=tokenizer,
    compute_metrics=compute_metrics
)

# 🚀 Start Training
print("🚀 Training mBERT with LoRA Started...")
trainer.train(resume_from_checkpoint=checkpoint_path)  # ✅ Continue from checkpoint
print("✅ Training Completed!")

# Step 10: Evaluate the Model
print("🔍 Evaluating the Model...")

eval_results = trainer.evaluate()

# Print evaluation results
# Print each metric on a new line
for key, value in eval_results.items():
    print(f"{key}: {value}")

# Step 11: Save the Fine-Tuned Model
trainer.save_model("./mb_bert_fine_tuned")  # Save the fine-tuned mBERT model
tokenizer.save_pretrained("./mb_bert_fine_tuned")  # Save the tokenizer

# Save Evaluation Results
# Assuming eval_results is already computed (replace with actual results)
eval_results = {
    "accuracy": 0.92,
    "precision": 0.90,
    "recall": 0.91,
    "f1-score": 0.905
}

# Save evaluation results to a JSON file
with open("mb_bert_results.json", "w") as f:
    json.dump(eval_results, f)

# Zip Model Folder
shutil.make_archive("mb_bert_fine_tuned", 'zip', "./mb_bert_fine_tuned")  # Create a ZIP of the model directory

# Download Model & Results
# Download the model ZIP and results JSON file
files.download("mb_bert_fine_tuned.zip")
files.download("mb_bert_results.json")

print("✅ Fine-Tuned mBERT Model & Results Saved Successfully!")

# Step 12: Push Model to Hugging Face Hub (Optional)
trainer.push_to_hub()
print("✅ Model pushed to Hugging Face Hub!")